### ISSUE TITLE
Events Stats is missing a few hours of data

### ISSUE THREAD

**Issue by Mika56** [grafana/sentry-datasource#273]
**What happened**:
Created a visualisation on Events Stats with a few filters. Data is missing from the start of the selected period. It seems to be related to timezone, as we're on CEST here, and it is missing exactly two hours of data.

**What you expected to happen**:
No data is missing :)

**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

![image](https://github.com/grafana/sentry-datasource/assets/600347/74010a1a-df74-45f1-8641-0340ecc34dd6)

**Anything else we need to know?**:
Other visualizations from other data sources, on the same dashboard, are not missing data. This issue is limited to Sentry data.

**Environment**:

- Grafana version: 11.0.0 (from Grafana's APT repository)
- Plugin version: 1.8.0
- OS Grafana is installed on: Debian
- User OS & Browser: Windows 11, Edge latest
- Others:

**Comment by alyssabull** [comment]
Hi @Mika56 - thanks for reporting this issue. I can replicate your problem when applying any of the quick time ranges (5m, 24h, etc.) as you mentioned. In the meantime, a workaround that was successful for me was selecting an absolute time range. I will continue to look into a fix but wanted to give you a temporary solution in the meantime. Thanks!

**Comment by alyssabull** [comment]
Hey @Mika56 thanks for reporting this issue. It looks like the timezone was not being set so I have fixed this here: https://github.com/grafana/sentry-datasource/pull/279
