### ISSUE TITLE
Sentry projects from dropdown menu hidden with panel.

### ISSUE THREAD

**Issue by forc3meat** [grafana/sentry-datasource#34]
Good day, team.

Currently got a beautiful bug on front - most of the projects could not be selected, because they're hidden with the visualization panel. Simple bug on frontend, which cause a lot of inconvenience.

Software:
Sentry v23.0
Grafana v8.2.7 (d2cccfe91e)

Steps to reproduce:
0. Generate >6 projects in the Sentry
1. Create new Grafana panel
2. Select Sentry datasource
3. Count available projects

ER: 
User can select from dropdown any available project to query 

AR: 
Projects dropdown opens up and hides with the visualization panel
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/39914768/163603096-47b6e165-cbe4-4c14-a6a3-5f3dc5631941.png">

Looks like it should open down

**Comment by aangelisc** [comment]
Tested and this is no longer an issue 😊
