### ISSUE TITLE
Sentry org tool tip not clear

### ISSUE THREAD

**Issue by joey-grafana** [grafana/sentry-datasource#36]
Update the `Sentry Org` tool tip to make it clearer what the user is supposed to only enter the `Sentry Org` into the input field and not the entire http string url.

i.e. use my-org
instead of https://sentry.io/organizations/my-org

![Screenshot 2022-06-30 at 09 13 04](https://user-images.githubusercontent.com/90795735/176627406-7b7a146c-a438-47a8-9706-08cd9f2095ff.png)

**Comment by lcpong1** [comment]
Thank you. I was having problems trying to connect to Sentry from Grafana exactly due to this.

**Comment by Taiwrash** [comment]
hello 👋 ,

I would love to jump on this. Can this be assigned to me?
