### ISSUE TITLE
Feature Request: Add support for events

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/sentry-datasource#37]
https://docs.sentry.io/api/discover/query-discover-events-in-table-format/

**Comment by zzuligy** [comment]
After integrate sentry,I found there is no event.It's so frustrate.

**Comment by jakubmank2** [comment]
Hello,
We are currently exploring the possibility of integrating Sentry data into our company's Grafana dashboard. The discover events endpoint plays a vital role in our integration plans.

I wanted to reach out and inquire about the estimated timeline for the availability of this feature. Could you please provide us with an update on when we can expect it to be ready for use?

Additionally, if there is anything I can assist you with during the development or testing phase, please do not hesitate to let me know. Your support in this matter is greatly appreciated.

Thank you and have a great day!

@yesoreyeram

**Comment by boweihanhf** [comment]
Is there a timeline for release for events support?

**Comment by DAcodedBEAT** [comment]
Hi @vickyyyyyyy / @aangelisc ! 👋 

Do you know when the next release of this plugin will be cut? It would be great to have this feature :)

**Comment by asimpson** [comment]
@DAcodedBEAT :wave: Hi, we should have a release out today or tomorrow, thanks!

**Comment by asimpson** [comment]
@DAcodedBEAT released [here](https://github.com/grafana/sentry-datasource/releases/tag/v1.4.0) :tada:
