### ISSUE TITLE
Sentry: Events query support

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/sentry-datasource#46]
Adding support for https://docs.sentry.io/api/discover/query-discover-events-in-table-format/

More details : 

https://raintank-corp.slack.com/archives/C02G20APV36/p1644914434851329?thread_ts=1644861430.433519&cid=C02G20APV36

https://raintank-corp.slack.com/archives/C02J0L4V4QL/p1653992132542589

**Comment by bossinc** [comment]
duplicate https://github.com/grafana/sentry-datasource/issues/37
